// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Dials1 = ui_Dials_create(ui_Screen1);
lv_obj_set_x( ui_Dials1, 0 );
lv_obj_set_y( ui_Dials1, 0 );














lv_obj_clear_flag( ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSPM25GROUP), LV_OBJ_FLAG_HIDDEN );    /// Flags



lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
