#pragma once
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

// Message passing parameters
#define TIME_UPDATE 1
#define PM25_LABEL_UPDATE 2
#define PM25_NUMERIC_UPDATE 3
#define TEMP_LABEL_UPDATE 4
#define TEMP_NUMERIC_UPDATE 5
#define HUMID_LABEL_UPDATE 6
#define HUMID_NUMERIC_UPDATE 7
#define PRESS_LABEL_UPDATE 8
#define PRESS_NUMERIC_UPDATE 9


#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// Animations
void SecondHandRotate_Animation( lv_obj_t *TargetObject, int delay);
void HourHandRotate_Animation( lv_obj_t *TargetObject, int delay);
void MinuteHandRotate_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_LoadingScreen
void ui_LoadingScreen_screen_init(void);
extern lv_obj_t *ui_LoadingScreen;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_Label1;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
struct screen1_time_service_params {
    lv_obj_t* obj;
    void (*updateTimeLabel)(lv_obj_t*);
};
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Dials1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
// Update functions
void updateLabel(lv_event_t *e);
void updateArc(lv_event_t *e);
void setVisibility(lv_event_t *e);

extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_ClockEdge01;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_caution_png);   // assets\caution.png
LV_IMG_DECLARE( ui_img_hourhand_png);   // assets\HourHand.png
LV_IMG_DECLARE( ui_img_minutehand_png);   // assets\MinuteHand.png
LV_IMG_DECLARE( ui_img_secondhand_png);   // assets\SecondHand.png
LV_IMG_DECLARE( ui_img_clockcenter_png);   // assets\ClockCenter.png



void ui_init( void );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
