// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT ClockEdge

lv_obj_t *ui_ClockEdge_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_ClockEdge;
cui_ClockEdge = lv_obj_create(comp_parent);
lv_obj_set_width( cui_ClockEdge, 480);
lv_obj_set_height( cui_ClockEdge, 480);
lv_obj_set_align( cui_ClockEdge, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ClockEdge, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(cui_ClockEdge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ClockEdge, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_ClockEdge, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgePM25Arc;
cui_ClockEdgePM25Arc = lv_arc_create(cui_ClockEdge);
lv_obj_set_width( cui_ClockEdgePM25Arc, 460);
lv_obj_set_height( cui_ClockEdgePM25Arc, 460);
lv_obj_set_align( cui_ClockEdgePM25Arc, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ClockEdgePM25Arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(cui_ClockEdgePM25Arc, 0,30);
lv_arc_set_value(cui_ClockEdgePM25Arc, 10);
lv_arc_set_bg_angles(cui_ClockEdgePM25Arc,160,200);
lv_obj_set_style_arc_width(cui_ClockEdgePM25Arc, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ClockEdgePM25Arc, lv_color_hex(0xFF9400), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ClockEdgePM25Arc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ClockEdgePM25Arc, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_ClockEdgePM25Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ClockEdgePM25Arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgePM25Label;
cui_ClockEdgePM25Label = lv_label_create(cui_ClockEdgePM25Arc);
lv_obj_set_width( cui_ClockEdgePM25Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockEdgePM25Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ClockEdgePM25Label, -180 );
lv_obj_set_y( cui_ClockEdgePM25Label, 0 );
lv_obj_set_align( cui_ClockEdgePM25Label, LV_ALIGN_CENTER );
lv_label_set_text(cui_ClockEdgePM25Label,"0 PM2.5");
lv_obj_clear_flag( cui_ClockEdgePM25Label, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_ClockEdgePM25Label, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ClockEdgePM25Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_ClockEdgePM25Label, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgePM25UpperBound;
cui_ClockEdgePM25UpperBound = lv_label_create(cui_ClockEdgePM25Arc);
lv_obj_set_width( cui_ClockEdgePM25UpperBound, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockEdgePM25UpperBound, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ClockEdgePM25UpperBound, -208 );
lv_obj_set_y( cui_ClockEdgePM25UpperBound, -92 );
lv_obj_set_align( cui_ClockEdgePM25UpperBound, LV_ALIGN_CENTER );
lv_label_set_text(cui_ClockEdgePM25UpperBound,"30");
lv_obj_clear_flag( cui_ClockEdgePM25UpperBound, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_ClockEdgePM25UpperBound, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ClockEdgePM25UpperBound, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_ClockEdgePM25UpperBound, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgePM25LowerBound;
cui_ClockEdgePM25LowerBound = lv_label_create(cui_ClockEdgePM25Arc);
lv_obj_set_width( cui_ClockEdgePM25LowerBound, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockEdgePM25LowerBound, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ClockEdgePM25LowerBound, -208 );
lv_obj_set_y( cui_ClockEdgePM25LowerBound, 92 );
lv_obj_set_align( cui_ClockEdgePM25LowerBound, LV_ALIGN_CENTER );
lv_label_set_text(cui_ClockEdgePM25LowerBound,"0");
lv_obj_clear_flag( cui_ClockEdgePM25LowerBound, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_ClockEdgePM25LowerBound, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ClockEdgePM25LowerBound, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_ClockEdgePM25LowerBound, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgeHumidityArc;
cui_ClockEdgeHumidityArc = lv_arc_create(cui_ClockEdge);
lv_obj_set_width( cui_ClockEdgeHumidityArc, 460);
lv_obj_set_height( cui_ClockEdgeHumidityArc, 460);
lv_obj_set_align( cui_ClockEdgeHumidityArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ClockEdgeHumidityArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_value(cui_ClockEdgeHumidityArc, 30);
lv_arc_set_bg_angles(cui_ClockEdgeHumidityArc,70,110);
lv_arc_set_mode(cui_ClockEdgeHumidityArc, LV_ARC_MODE_REVERSE);
lv_obj_set_style_arc_width(cui_ClockEdgeHumidityArc, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ClockEdgeHumidityArc, lv_color_hex(0x00D6FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ClockEdgeHumidityArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ClockEdgeHumidityArc, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_ClockEdgeHumidityArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ClockEdgeHumidityArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgeHumidityLabel;
cui_ClockEdgeHumidityLabel = lv_label_create(cui_ClockEdgeHumidityArc);
lv_obj_set_width( cui_ClockEdgeHumidityLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockEdgeHumidityLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ClockEdgeHumidityLabel, 0 );
lv_obj_set_y( cui_ClockEdgeHumidityLabel, 210 );
lv_obj_set_align( cui_ClockEdgeHumidityLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_ClockEdgeHumidityLabel,"100% RH");
lv_obj_clear_flag( cui_ClockEdgeHumidityLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_ClockEdgeHumidityLabel, lv_color_hex(0x00D6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ClockEdgeHumidityLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_ClockEdgeHumidityLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgeHumidityLowerBound;
cui_ClockEdgeHumidityLowerBound = lv_label_create(cui_ClockEdgeHumidityArc);
lv_obj_set_width( cui_ClockEdgeHumidityLowerBound, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockEdgeHumidityLowerBound, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ClockEdgeHumidityLowerBound, -88 );
lv_obj_set_y( cui_ClockEdgeHumidityLowerBound, 208 );
lv_obj_set_align( cui_ClockEdgeHumidityLowerBound, LV_ALIGN_CENTER );
lv_label_set_text(cui_ClockEdgeHumidityLowerBound,"0");
lv_obj_clear_flag( cui_ClockEdgeHumidityLowerBound, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_ClockEdgeHumidityLowerBound, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ClockEdgeHumidityLowerBound, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_ClockEdgeHumidityLowerBound, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgeHumidityUpperBound;
cui_ClockEdgeHumidityUpperBound = lv_label_create(cui_ClockEdgeHumidityArc);
lv_obj_set_width( cui_ClockEdgeHumidityUpperBound, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockEdgeHumidityUpperBound, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ClockEdgeHumidityUpperBound, 92 );
lv_obj_set_y( cui_ClockEdgeHumidityUpperBound, 208 );
lv_obj_set_align( cui_ClockEdgeHumidityUpperBound, LV_ALIGN_CENTER );
lv_label_set_text(cui_ClockEdgeHumidityUpperBound,"100");
lv_obj_clear_flag( cui_ClockEdgeHumidityUpperBound, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_ClockEdgeHumidityUpperBound, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ClockEdgeHumidityUpperBound, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_ClockEdgeHumidityUpperBound, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgePressureArc;
cui_ClockEdgePressureArc = lv_arc_create(cui_ClockEdge);
lv_obj_set_width( cui_ClockEdgePressureArc, 460);
lv_obj_set_height( cui_ClockEdgePressureArc, 460);
lv_obj_set_align( cui_ClockEdgePressureArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ClockEdgePressureArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(cui_ClockEdgePressureArc, 85,95);
lv_arc_set_value(cui_ClockEdgePressureArc, 88);
lv_arc_set_bg_angles(cui_ClockEdgePressureArc,340,20);
lv_arc_set_mode(cui_ClockEdgePressureArc, LV_ARC_MODE_REVERSE);
lv_obj_set_style_arc_width(cui_ClockEdgePressureArc, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ClockEdgePressureArc, lv_color_hex(0x00CC5A), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ClockEdgePressureArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ClockEdgePressureArc, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_ClockEdgePressureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ClockEdgePressureArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgePressureLabel;
cui_ClockEdgePressureLabel = lv_label_create(cui_ClockEdgePressureArc);
lv_obj_set_width( cui_ClockEdgePressureLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockEdgePressureLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ClockEdgePressureLabel, 180 );
lv_obj_set_y( cui_ClockEdgePressureLabel, 0 );
lv_obj_set_align( cui_ClockEdgePressureLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_ClockEdgePressureLabel,"87.7 kPa");
lv_obj_clear_flag( cui_ClockEdgePressureLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_ClockEdgePressureLabel, lv_color_hex(0x00CC5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ClockEdgePressureLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_ClockEdgePressureLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgePressureUpperBound;
cui_ClockEdgePressureUpperBound = lv_label_create(cui_ClockEdgePressureArc);
lv_obj_set_width( cui_ClockEdgePressureUpperBound, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockEdgePressureUpperBound, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ClockEdgePressureUpperBound, 208 );
lv_obj_set_y( cui_ClockEdgePressureUpperBound, -92 );
lv_obj_set_align( cui_ClockEdgePressureUpperBound, LV_ALIGN_CENTER );
lv_label_set_text(cui_ClockEdgePressureUpperBound,"95");
lv_obj_clear_flag( cui_ClockEdgePressureUpperBound, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_ClockEdgePressureUpperBound, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ClockEdgePressureUpperBound, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_ClockEdgePressureUpperBound, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgePressureLowerBound;
cui_ClockEdgePressureLowerBound = lv_label_create(cui_ClockEdgePressureArc);
lv_obj_set_width( cui_ClockEdgePressureLowerBound, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockEdgePressureLowerBound, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ClockEdgePressureLowerBound, 208 );
lv_obj_set_y( cui_ClockEdgePressureLowerBound, 92 );
lv_obj_set_align( cui_ClockEdgePressureLowerBound, LV_ALIGN_CENTER );
lv_label_set_text(cui_ClockEdgePressureLowerBound,"85");
lv_obj_clear_flag( cui_ClockEdgePressureLowerBound, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_ClockEdgePressureLowerBound, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ClockEdgePressureLowerBound, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_ClockEdgePressureLowerBound, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgeTemperatureArc;
cui_ClockEdgeTemperatureArc = lv_arc_create(cui_ClockEdge);
lv_obj_set_width( cui_ClockEdgeTemperatureArc, 460);
lv_obj_set_height( cui_ClockEdgeTemperatureArc, 460);
lv_obj_set_align( cui_ClockEdgeTemperatureArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ClockEdgeTemperatureArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(cui_ClockEdgeTemperatureArc, -30,30);
lv_arc_set_value(cui_ClockEdgeTemperatureArc, 10);
lv_arc_set_bg_angles(cui_ClockEdgeTemperatureArc,250,290);
lv_obj_set_style_arc_width(cui_ClockEdgeTemperatureArc, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ClockEdgeTemperatureArc, lv_color_hex(0xFF585B), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ClockEdgeTemperatureArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ClockEdgeTemperatureArc, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_ClockEdgeTemperatureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ClockEdgeTemperatureArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgeTemperatureLabel;
cui_ClockEdgeTemperatureLabel = lv_label_create(cui_ClockEdgeTemperatureArc);
lv_obj_set_width( cui_ClockEdgeTemperatureLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockEdgeTemperatureLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ClockEdgeTemperatureLabel, 0 );
lv_obj_set_y( cui_ClockEdgeTemperatureLabel, -210 );
lv_obj_set_align( cui_ClockEdgeTemperatureLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_ClockEdgeTemperatureLabel,"10.2 °C");
lv_obj_clear_flag( cui_ClockEdgeTemperatureLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_ClockEdgeTemperatureLabel, lv_color_hex(0xFF585B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ClockEdgeTemperatureLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_ClockEdgeTemperatureLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgeTemperatureLowerBound;
cui_ClockEdgeTemperatureLowerBound = lv_label_create(cui_ClockEdgeTemperatureArc);
lv_obj_set_width( cui_ClockEdgeTemperatureLowerBound, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockEdgeTemperatureLowerBound, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ClockEdgeTemperatureLowerBound, -92 );
lv_obj_set_y( cui_ClockEdgeTemperatureLowerBound, -208 );
lv_obj_set_align( cui_ClockEdgeTemperatureLowerBound, LV_ALIGN_CENTER );
lv_label_set_text(cui_ClockEdgeTemperatureLowerBound,"-30");
lv_obj_clear_flag( cui_ClockEdgeTemperatureLowerBound, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_ClockEdgeTemperatureLowerBound, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ClockEdgeTemperatureLowerBound, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_ClockEdgeTemperatureLowerBound, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgeTemperatureUpperBound;
cui_ClockEdgeTemperatureUpperBound = lv_label_create(cui_ClockEdgeTemperatureArc);
lv_obj_set_width( cui_ClockEdgeTemperatureUpperBound, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockEdgeTemperatureUpperBound, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ClockEdgeTemperatureUpperBound, 92 );
lv_obj_set_y( cui_ClockEdgeTemperatureUpperBound, -208 );
lv_obj_set_align( cui_ClockEdgeTemperatureUpperBound, LV_ALIGN_CENTER );
lv_label_set_text(cui_ClockEdgeTemperatureUpperBound,"30");
lv_obj_clear_flag( cui_ClockEdgeTemperatureUpperBound, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_ClockEdgeTemperatureUpperBound, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_ClockEdgeTemperatureUpperBound, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_ClockEdgeTemperatureUpperBound, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ClockEdgeClockGroup;
cui_ClockEdgeClockGroup = lv_obj_create(cui_ClockEdge);
lv_obj_set_width( cui_ClockEdgeClockGroup, 480);
lv_obj_set_height( cui_ClockEdgeClockGroup, 480);
lv_obj_set_align( cui_ClockEdgeClockGroup, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ClockEdgeClockGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(cui_ClockEdgeClockGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ClockEdgeClockGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_ClockEdgeClockGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_HourHand;
cui_HourHand = lv_img_create(cui_ClockEdgeClockGroup);
lv_img_set_src(cui_HourHand, &ui_img_hourhand_png);
lv_obj_set_width( cui_HourHand, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_HourHand, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_HourHand, 80 );
lv_obj_set_y( cui_HourHand, 0 );
lv_obj_set_align( cui_HourHand, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_HourHand, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_pivot(cui_HourHand,4,4);
lv_img_set_angle(cui_HourHand,300);

lv_obj_t *cui_MinuteHand;
cui_MinuteHand = lv_img_create(cui_ClockEdgeClockGroup);
lv_img_set_src(cui_MinuteHand, &ui_img_minutehand_png);
lv_obj_set_width( cui_MinuteHand, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_MinuteHand, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_MinuteHand, 106 );
lv_obj_set_y( cui_MinuteHand, 0 );
lv_obj_set_align( cui_MinuteHand, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_MinuteHand, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_pivot(cui_MinuteHand,3,3);
lv_img_set_angle(cui_MinuteHand,2550);

lv_obj_t *cui_SecondHand;
cui_SecondHand = lv_img_create(cui_ClockEdgeClockGroup);
lv_img_set_src(cui_SecondHand, &ui_img_secondhand_png);
lv_obj_set_width( cui_SecondHand, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_SecondHand, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_SecondHand, 107 );
lv_obj_set_y( cui_SecondHand, 0 );
lv_obj_set_align( cui_SecondHand, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_SecondHand, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_pivot(cui_SecondHand,2,2);
lv_img_set_angle(cui_SecondHand,1800);

lv_obj_t *cui_ClockCenter;
cui_ClockCenter = lv_img_create(cui_ClockEdgeClockGroup);
lv_img_set_src(cui_ClockCenter, &ui_img_clockcenter_png);
lv_obj_set_width( cui_ClockCenter, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ClockCenter, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_ClockCenter, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ClockCenter, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_angle(cui_ClockCenter,1);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CLOCKEDGE_NUM);
children[UI_COMP_CLOCKEDGE_CLOCKEDGE] = cui_ClockEdge;
children[UI_COMP_CLOCKEDGE_CLOCKEDGEPM25ARC] = cui_ClockEdgePM25Arc;
children[UI_COMP_CLOCKEDGE_CLOCKEDGEPM25ARC_CLOCKEDGEPM25LABEL] = cui_ClockEdgePM25Label;
children[UI_COMP_CLOCKEDGE_CLOCKEDGEPM25ARC_CLOCKEDGEPM25UPPERBOUND] = cui_ClockEdgePM25UpperBound;
children[UI_COMP_CLOCKEDGE_CLOCKEDGEPM25ARC_CLOCKEDGEPM25LOWERBOUND] = cui_ClockEdgePM25LowerBound;
children[UI_COMP_CLOCKEDGE_CLOCKEDGEHUMIDITYARC] = cui_ClockEdgeHumidityArc;
children[UI_COMP_CLOCKEDGE_CLOCKEDGEHUMIDITYARC_CLOCKEDGEHUMIDITYLABEL] = cui_ClockEdgeHumidityLabel;
children[UI_COMP_CLOCKEDGE_CLOCKEDGEHUMIDITYARC_CLOCKEDGEHUMIDITYLOWERBOUND] = cui_ClockEdgeHumidityLowerBound;
children[UI_COMP_CLOCKEDGE_CLOCKEDGEHUMIDITYARC_CLOCKEDGEHUMIDITYUPPERBOUND] = cui_ClockEdgeHumidityUpperBound;
children[UI_COMP_CLOCKEDGE_CLOCKEDGEPRESSUREARC] = cui_ClockEdgePressureArc;
children[UI_COMP_CLOCKEDGE_CLOCKEDGEPRESSUREARC_CLOCKEDGEPRESSURELABEL] = cui_ClockEdgePressureLabel;
children[UI_COMP_CLOCKEDGE_CLOCKEDGEPRESSUREARC_CLOCKEDGEPRESSUREUPPERBOUND] = cui_ClockEdgePressureUpperBound;
children[UI_COMP_CLOCKEDGE_CLOCKEDGEPRESSUREARC_CLOCKEDGEPRESSURELOWERBOUND] = cui_ClockEdgePressureLowerBound;
children[UI_COMP_CLOCKEDGE_CLOCKEDGETEMPERATUREARC] = cui_ClockEdgeTemperatureArc;
children[UI_COMP_CLOCKEDGE_CLOCKEDGETEMPERATUREARC_CLOCKEDGETEMPERATURELABEL] = cui_ClockEdgeTemperatureLabel;
children[UI_COMP_CLOCKEDGE_CLOCKEDGETEMPERATUREARC_CLOCKEDGETEMPERATURELOWERBOUND] = cui_ClockEdgeTemperatureLowerBound;
children[UI_COMP_CLOCKEDGE_CLOCKEDGETEMPERATUREARC_CLOCKEDGETEMPERATUREUPPERBOUND] = cui_ClockEdgeTemperatureUpperBound;
children[UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP] = cui_ClockEdgeClockGroup;
children[UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_HOURHAND] = cui_HourHand;
children[UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_MINUTEHAND] = cui_MinuteHand;
children[UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_SECONDHAND] = cui_SecondHand;
children[UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_CLOCKCENTER] = cui_ClockCenter;
lv_obj_add_event_cb(cui_ClockEdge, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_ClockEdge, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_ClockEdge_create_hook(cui_ClockEdge);
return cui_ClockEdge; 
}

