// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Dials

lv_obj_t *ui_Dials_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Dials;
cui_Dials = lv_obj_create(comp_parent);
lv_obj_set_width( cui_Dials, 480);
lv_obj_set_height( cui_Dials, 480);
lv_obj_set_align( cui_Dials, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_Dials, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(cui_Dials, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Dials, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_Dials, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DialsHumidityGroup;
cui_DialsHumidityGroup = lv_obj_create(cui_Dials);
lv_obj_set_width( cui_DialsHumidityGroup, 480);
lv_obj_set_height( cui_DialsHumidityGroup, 480);
lv_obj_set_align( cui_DialsHumidityGroup, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_DialsHumidityGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(cui_DialsHumidityGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_DialsHumidityGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_DialsHumidityGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DialsHumidityArc;
cui_DialsHumidityArc = lv_arc_create(cui_DialsHumidityGroup);
lv_obj_set_width( cui_DialsHumidityArc, 300);
lv_obj_set_height( cui_DialsHumidityArc, 300);
lv_obj_set_align( cui_DialsHumidityArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_DialsHumidityArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_value(cui_DialsHumidityArc, 87);
lv_arc_set_bg_angles(cui_DialsHumidityArc,145,35);
lv_obj_set_style_arc_color(cui_DialsHumidityArc, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_DialsHumidityArc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_DialsHumidityArc, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_DialsHumidityArc, lv_color_hex(0x00D6FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_DialsHumidityArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_DialsHumidityArc, 30, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_DialsHumidityArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_DialsHumidityArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_DialsHumidityLabel;
cui_DialsHumidityLabel = lv_label_create(cui_DialsHumidityGroup);
lv_obj_set_width( cui_DialsHumidityLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_DialsHumidityLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_DialsHumidityLabel, 0 );
lv_obj_set_y( cui_DialsHumidityLabel, 90 );
lv_obj_set_align( cui_DialsHumidityLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_DialsHumidityLabel,"87 %rh");
lv_obj_clear_flag( cui_DialsHumidityLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_DialsHumidityLabel, lv_color_hex(0x00D6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_DialsHumidityLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_DialsHumidityLabel, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DialsPressureGroup;
cui_DialsPressureGroup = lv_obj_create(cui_Dials);
lv_obj_set_width( cui_DialsPressureGroup, 480);
lv_obj_set_height( cui_DialsPressureGroup, 480);
lv_obj_set_align( cui_DialsPressureGroup, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_DialsPressureGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(cui_DialsPressureGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_DialsPressureGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_DialsPressureGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DialsPressureArc;
cui_DialsPressureArc = lv_arc_create(cui_DialsPressureGroup);
lv_obj_set_width( cui_DialsPressureArc, 380);
lv_obj_set_height( cui_DialsPressureArc, 380);
lv_obj_set_align( cui_DialsPressureArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_DialsPressureArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(cui_DialsPressureArc, 85,92);
lv_arc_set_value(cui_DialsPressureArc, 88);
lv_arc_set_bg_angles(cui_DialsPressureArc,127,53);
lv_obj_set_style_arc_color(cui_DialsPressureArc, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_DialsPressureArc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_DialsPressureArc, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_DialsPressureArc, lv_color_hex(0x00CC5A), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_DialsPressureArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_DialsPressureArc, 30, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_DialsPressureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_DialsPressureArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_DialsPressureLabel;
cui_DialsPressureLabel = lv_label_create(cui_DialsPressureGroup);
lv_obj_set_width( cui_DialsPressureLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_DialsPressureLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_DialsPressureLabel, 0 );
lv_obj_set_y( cui_DialsPressureLabel, 147 );
lv_obj_set_align( cui_DialsPressureLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_DialsPressureLabel,"87.9 kPa");
lv_obj_clear_flag( cui_DialsPressureLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_DialsPressureLabel, lv_color_hex(0x00CC5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_DialsPressureLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_DialsPressureLabel, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DialsTemperatureGroup;
cui_DialsTemperatureGroup = lv_obj_create(cui_Dials);
lv_obj_set_width( cui_DialsTemperatureGroup, 480);
lv_obj_set_height( cui_DialsTemperatureGroup, 480);
lv_obj_set_align( cui_DialsTemperatureGroup, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_DialsTemperatureGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(cui_DialsTemperatureGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_DialsTemperatureGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_DialsTemperatureGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DialsTemperatureArc;
cui_DialsTemperatureArc = lv_arc_create(cui_DialsTemperatureGroup);
lv_obj_set_width( cui_DialsTemperatureArc, 460);
lv_obj_set_height( cui_DialsTemperatureArc, 460);
lv_obj_set_align( cui_DialsTemperatureArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_DialsTemperatureArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(cui_DialsTemperatureArc, -30,40);
lv_arc_set_value(cui_DialsTemperatureArc, 2);
lv_arc_set_bg_angles(cui_DialsTemperatureArc,118,62);
lv_obj_set_style_arc_color(cui_DialsTemperatureArc, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_DialsTemperatureArc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_DialsTemperatureArc, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_DialsTemperatureArc, lv_color_hex(0xFF585B), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_DialsTemperatureArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_DialsTemperatureArc, 30, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_DialsTemperatureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_DialsTemperatureArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_DialsTemperatureLabel;
cui_DialsTemperatureLabel = lv_label_create(cui_DialsTemperatureGroup);
lv_obj_set_width( cui_DialsTemperatureLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_DialsTemperatureLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_DialsTemperatureLabel, 0 );
lv_obj_set_y( cui_DialsTemperatureLabel, 200 );
lv_obj_set_align( cui_DialsTemperatureLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_DialsTemperatureLabel,"2.27 °C");
lv_obj_clear_flag( cui_DialsTemperatureLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_DialsTemperatureLabel, lv_color_hex(0xFF585B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_DialsTemperatureLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_DialsTemperatureLabel, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DialsTimeLabel;
cui_DialsTimeLabel = lv_label_create(cui_Dials);
lv_obj_set_width( cui_DialsTimeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_DialsTimeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_DialsTimeLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_DialsTimeLabel,"8:37 am");
lv_obj_clear_flag( cui_DialsTimeLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(cui_DialsTimeLabel, lv_color_hex(0x848484), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_DialsTimeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_DialsTimeLabel, &lv_font_montserrat_46, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DialsPM25Group;
cui_DialsPM25Group = lv_obj_create(cui_Dials);
lv_obj_set_width( cui_DialsPM25Group, 151);
lv_obj_set_height( cui_DialsPM25Group, 140);
lv_obj_set_x( cui_DialsPM25Group, -13 );
lv_obj_set_y( cui_DialsPM25Group, -49 );
lv_obj_set_align( cui_DialsPM25Group, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_DialsPM25Group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_DialsPM25Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_DialsPM25Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_DialsPM25Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DialsPM25Img;
cui_DialsPM25Img = lv_img_create(cui_DialsPM25Group);
lv_img_set_src(cui_DialsPM25Img, &ui_img_caution_png);
lv_obj_set_width( cui_DialsPM25Img, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_DialsPM25Img, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_DialsPM25Img, -40 );
lv_obj_set_y( cui_DialsPM25Img, -10 );
lv_obj_set_align( cui_DialsPM25Img, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_DialsPM25Img, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_DialsPM25Img, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_DialsPM25Label;
cui_DialsPM25Label = lv_label_create(cui_DialsPM25Group);
lv_obj_set_width( cui_DialsPM25Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_DialsPM25Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_DialsPM25Label, 31 );
lv_obj_set_y( cui_DialsPM25Label, -6 );
lv_obj_set_align( cui_DialsPM25Label, LV_ALIGN_CENTER );
lv_label_set_text(cui_DialsPM25Label,"PM2.5");
lv_obj_set_style_text_color(cui_DialsPM25Label, lv_color_hex(0xFFD629), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_DialsPM25Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_DialsPM25Label, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DIALS_NUM);
children[UI_COMP_DIALS_DIALS] = cui_Dials;
children[UI_COMP_DIALS_DIALSHUMIDITYGROUP] = cui_DialsHumidityGroup;
children[UI_COMP_DIALS_DIALSHUMIDITYGROUP_DIALSHUMIDITYARC] = cui_DialsHumidityArc;
children[UI_COMP_DIALS_DIALSHUMIDITYGROUP_DIALSHUMIDITYLABEL] = cui_DialsHumidityLabel;
children[UI_COMP_DIALS_DIALSPRESSUREGROUP] = cui_DialsPressureGroup;
children[UI_COMP_DIALS_DIALSPRESSUREGROUP_DIALSPRESSUREARC] = cui_DialsPressureArc;
children[UI_COMP_DIALS_DIALSPRESSUREGROUP_DIALSPRESSURELABEL] = cui_DialsPressureLabel;
children[UI_COMP_DIALS_DIALSTEMPERATUREGROUP] = cui_DialsTemperatureGroup;
children[UI_COMP_DIALS_DIALSTEMPERATUREGROUP_DIALSTEMPERATUREARC] = cui_DialsTemperatureArc;
children[UI_COMP_DIALS_DIALSTEMPERATUREGROUP_DIALSTEMPERATURELABEL] = cui_DialsTemperatureLabel;
children[UI_COMP_DIALS_DIALSTIMELABEL] = cui_DialsTimeLabel;
children[UI_COMP_DIALS_DIALSPM25GROUP] = cui_DialsPM25Group;
children[UI_COMP_DIALS_DIALSPM25GROUP_DIALSPM25IMG] = cui_DialsPM25Img;
children[UI_COMP_DIALS_DIALSPM25GROUP_DIALSPM25LABEL] = cui_DialsPM25Label;
lv_obj_add_event_cb(cui_Dials, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Dials, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Dials_create_hook(cui_Dials);
return cui_Dials; 
}

