// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"
#include <Arduino.h>

int16_t hourAngle;
int16_t minAngle;
int16_t secAngle;
static TaskHandle_t screen2_timekeeping_task;


void screen2UpdateTime(lv_event_t *e);
void updateClockHands();
void startClockAnimations();
int16_t calculateClockAngle(float percentRotate);

void clockUpdateTask();
void clockUpdateFn(void* params);

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ClockEdge01 = ui_ClockEdge_create(ui_Screen2);
lv_obj_set_x( ui_ClockEdge01, 0 );
lv_obj_set_y( ui_ClockEdge01, 0 );
lv_obj_clear_flag( ui_ClockEdge01, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags





















lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);
// Temperature Update
lv_msg_subsribe_obj(TEMP_LABEL_UPDATE, ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGETEMPERATUREARC_CLOCKEDGETEMPERATURELABEL), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGETEMPERATUREARC_CLOCKEDGETEMPERATURELABEL),
    updateLabel,
LV_EVENT_MSG_RECEIVED, NULL);
lv_msg_subsribe_obj(TEMP_NUMERIC_UPDATE, ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGETEMPERATUREARC), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGETEMPERATUREARC),
    updateArc,
LV_EVENT_MSG_RECEIVED, NULL);

// Pressure Update
lv_msg_subsribe_obj(PRESS_LABEL_UPDATE, ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGEPRESSUREARC_CLOCKEDGEPRESSURELABEL), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGEPRESSUREARC_CLOCKEDGEPRESSURELABEL),
    updateLabel,
LV_EVENT_MSG_RECEIVED, NULL);
lv_msg_subsribe_obj(PRESS_NUMERIC_UPDATE, ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGEPRESSUREARC), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGEPRESSUREARC),
    updateArc,
LV_EVENT_MSG_RECEIVED, NULL);

// Humidity Update
lv_msg_subsribe_obj(HUMID_LABEL_UPDATE, ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGEHUMIDITYARC_CLOCKEDGEHUMIDITYLABEL), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGEHUMIDITYARC_CLOCKEDGEHUMIDITYLABEL),
    updateLabel,
LV_EVENT_MSG_RECEIVED, NULL);
lv_msg_subsribe_obj(HUMID_NUMERIC_UPDATE, ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGEHUMIDITYARC), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGEHUMIDITYARC),
    updateArc,
LV_EVENT_MSG_RECEIVED, NULL);

// PM2.5 Update
lv_msg_subsribe_obj(PM25_LABEL_UPDATE, ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGEPM25ARC_CLOCKEDGEPM25LABEL), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGEPM25ARC_CLOCKEDGEPM25LABEL),
    updateLabel,
LV_EVENT_MSG_RECEIVED, NULL);
lv_msg_subsribe_obj(PM25_NUMERIC_UPDATE, ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGEPM25ARC), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGEPM25ARC),
    updateArc,
LV_EVENT_MSG_RECEIVED, NULL);

// Time Update
lv_msg_subsribe_obj(TIME_UPDATE, ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGE), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGE),
    screen2UpdateTime,
LV_EVENT_MSG_RECEIVED, NULL);

// Start clock animations
// startClockAnimations();
// clockUpdateTask();
}

void screen2UpdateTime(lv_event_t *e){
    if(screen2_timekeeping_task != NULL){
        vTaskDelete(screen2_timekeeping_task);
    }
    lv_anim_del_all();
    lv_obj_t *label = (lv_obj_t *)lv_event_get_target(e);
    lv_msg_t *m = lv_event_get_msg(e);
    int16_t (*newTime)[3] = ((int16_t*)lv_msg_get_payload(m));
    int16_t hour12 = ((*newTime)[0])%12;
    float secondRotatePercent = (float)(*newTime)[2]/60;
    float minuteRotatePercent = (float)(*newTime)[1]/60;
    minuteRotatePercent += secondRotatePercent/60; // Add fractional angles from seconds (second percent)*(1/60)
    float hourRotatePercent = (float)hour12/12;
    hourRotatePercent += minuteRotatePercent/12;

    hourAngle = calculateClockAngle(hourRotatePercent);
    minAngle = calculateClockAngle(minuteRotatePercent);
    secAngle = calculateClockAngle(secondRotatePercent);
    // lv_anim_del_all();
    updateClockHands();
    // startClockAnimations();
    clockUpdateTask();
}

int16_t calculateClockAngle(float percentRotate){
    float angle = 3600 * percentRotate;
    int16_t iangle = round(angle) - 900; // Angle 0 is pointing to the right
    if(iangle < 0){
        iangle = 3600 + iangle;
    }
    return iangle;
}

void updateClockHands(){
    lv_img_set_angle(ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_SECONDHAND), secAngle);
    lv_img_set_angle(ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_MINUTEHAND), minAngle);
    lv_img_set_angle(ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_HOURHAND), hourAngle);
}

void clockUpdateFn(void* params){
    const TickType_t delayTime = 60000;
    TickType_t lastWakeTime = 0;
    while(1){
        lv_anim_del_all();
        SecondHandRotate_Animation(ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_SECONDHAND), 0);
        MinuteHandRotate_Animation(ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_MINUTEHAND), 0);
        HourHandRotate_Animation(ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_HOURHAND), 0);
        xTaskDelayUntil( &lastWakeTime, delayTime );
    }
    vTaskDelete(NULL);
}

void clockUpdateTask(){
    xTaskCreate(clockUpdateFn, "screen2_clock_task", 1024*6, NULL, 1, &screen2_timekeeping_task);
}

// void startClockAnimations(){
//     SecondHandRotate_Animation(ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_SECONDHAND), 0);
//     // MinuteHandRotate_Animation(ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_MINUTEHAND), 0);
//     // HourHandRotate_Animation(ui_comp_get_child(ui_ClockEdge01, UI_COMP_CLOCKEDGE_CLOCKEDGECLOCKGROUP_HOURHAND), 0);
// }