// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"
#include <Arduino.h>

int16_t hour;
int16_t min;
int16_t sec;

static TaskHandle_t screen1_timekeeping_task;
struct screen1_time_service_params time_params;

void updateTimeLabel(lv_obj_t *timeLabel);
void timeUpdateTask(lv_obj_t *displayLabel);
void timeUpdateFn(void* params);
void screen1UpdateTime(lv_event_t *e);

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Dials1 = ui_Dials_create(ui_Screen1);
lv_obj_set_x( ui_Dials1, 0 );
lv_obj_set_y( ui_Dials1, 0 );

















lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

// Temperature Update
lv_msg_subsribe_obj(TEMP_LABEL_UPDATE, ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSTEMPERATUREGROUP_DIALSTEMPERATURELABEL), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSTEMPERATUREGROUP_DIALSTEMPERATURELABEL),
    updateLabel,
LV_EVENT_MSG_RECEIVED, NULL);
lv_msg_subsribe_obj(TEMP_NUMERIC_UPDATE, ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSTEMPERATUREGROUP_DIALSTEMPERATUREARC), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSTEMPERATUREGROUP_DIALSTEMPERATUREARC),
    updateArc,
LV_EVENT_MSG_RECEIVED, NULL);

// Pressure Update
lv_msg_subsribe_obj(PRESS_LABEL_UPDATE, ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSPRESSUREGROUP_DIALSPRESSURELABEL), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSPRESSUREGROUP_DIALSPRESSURELABEL),
    updateLabel,
LV_EVENT_MSG_RECEIVED, NULL);
lv_msg_subsribe_obj(PRESS_NUMERIC_UPDATE, ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSPRESSUREGROUP_DIALSPRESSUREARC), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSPRESSUREGROUP_DIALSPRESSUREARC),
    updateArc,
LV_EVENT_MSG_RECEIVED, NULL);

// Humidity Update
lv_msg_subsribe_obj(HUMID_LABEL_UPDATE, ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSHUMIDITYGROUP_DIALSHUMIDITYLABEL), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSHUMIDITYGROUP_DIALSHUMIDITYLABEL),
    updateLabel,
LV_EVENT_MSG_RECEIVED, NULL);
lv_msg_subsribe_obj(HUMID_NUMERIC_UPDATE, ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSHUMIDITYGROUP_DIALSHUMIDITYARC), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSHUMIDITYGROUP_DIALSHUMIDITYARC),
    updateArc,
LV_EVENT_MSG_RECEIVED, NULL);

// PM2.5 Update
lv_msg_subsribe_obj(PM25_NUMERIC_UPDATE, ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSPM25GROUP_DIALSPM25IMG), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSPM25GROUP_DIALSPM25IMG),
    setVisibility,
LV_EVENT_MSG_RECEIVED, NULL);
lv_msg_subsribe_obj(PM25_NUMERIC_UPDATE, ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSPM25GROUP_DIALSPM25LABEL), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSPM25GROUP_DIALSPM25LABEL),
    setVisibility,
LV_EVENT_MSG_RECEIVED, NULL);


// Time Update
lv_msg_subsribe_obj(TIME_UPDATE, ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSTIMELABEL), NULL);
lv_obj_add_event_cb(
    ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSTIMELABEL),
    screen1UpdateTime,
LV_EVENT_MSG_RECEIVED, NULL);

// Start timekeeping task
timeUpdateTask(ui_comp_get_child(ui_Dials1, UI_COMP_DIALS_DIALSTIMELABEL));
}

void screen1UpdateTime(lv_event_t *e){
    lv_obj_t *label = (lv_obj_t *)lv_event_get_target(e);
    lv_msg_t *m = lv_event_get_msg(e);
    int16_t (*newTime)[3] = ((int16_t*)lv_msg_get_payload(m));
    hour = (*newTime)[0];
    min = (*newTime)[1];
    sec = (*newTime)[2];
    updateTimeLabel(label);
}

void updateTimeLabel(lv_obj_t* displayLabel){
    char hour_str[3];
    char min_str[3];
    char timeLabel[10];
    bool isPM = hour/12;
    uint16_t hour12 = hour%12;
    if(hour12 == 0){
        hour12 = 12;
    }
    sprintf(hour_str, "%d", hour12);
    sprintf(min_str, "%d", min);

    strcpy(timeLabel, hour_str);
    strcat(timeLabel, ":");
    if(min < 10){
        strcat(timeLabel, "0");
    }
    strcat(timeLabel, min_str);

    if(isPM){
        strcat(timeLabel, " PM");
    }else{
        strcat(timeLabel, " AM");
    }
    lv_label_set_text_fmt(displayLabel, timeLabel);
}

void timeUpdateFn(void* params){
    struct screen1_time_service_params time_params = *((struct screen1_time_service_params*)params);
    const TickType_t everySecond = 1000;
    TickType_t lastWakeTime = xTaskGetTickCount();
    while(1){
        xTaskDelayUntil( &lastWakeTime, everySecond );
        if(sec == 59){
            sec = 0;
            if(min == 59){
                min = 0;
                if(hour == 23){
                    hour = 0;
                }else{
                    hour++;
                }
            }else{
                min++;
            }
            time_params.updateTimeLabel(time_params.obj);
        }else{
            sec++;
        }
    }
    vTaskDelete(NULL);
}

void timeUpdateTask(lv_obj_t *displayLabel){
    time_params.obj = displayLabel;
    time_params.updateTimeLabel = &updateTimeLabel;
    xTaskCreate(timeUpdateFn, "screen1_time_task", 1024*6, &time_params, 1, &screen1_timekeeping_task);
}